# Generated by Django 5.0.6 on 2024-07-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_coffee_fruitjuice_mlik_mocktail_softdrinks_tea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mlik',
            new_name='MilkandMilkshake',
        ),
    ]
